services:
  - type: web
    name: amptalentiq-proc
    env: python
    # We use the native python environment
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: YOLO_MODEL_PATH
        value: yolov8n.pt # Use the standard name so it downloads automatically if missing